### ISSUE TITLE
ssh access

### ISSUE THREAD

**Issue by AlexMarin** [NasaAppChallenge/birdseye-server#13]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaCksX9tAEGRPPW8ly+BSpdZBmCdK1kCgqwZ5naaxEiwAOP5pA1cizcTE4Rn1IyxSKIPE6k7wjNsL+h2yYFDAi9BDYadRW0dUyU6EUiCsDt0x9dAa8v2AwK3RW4tM2UaEcbWaa7XA7XU0isW5WRo5TQGzeYc+53Oefj5T5WyYFJu/ml8e+kBHe1HemFkO6sXiZdzw2pwn4boPnDvIKcW5Cq9Hm4VOx/wt7SkeCuafKe8DcA0fG+G1vwkKfKS7YlHLaGLUlyhyxBQBpUAapRpD6Yts93fQOQVfkfLhunICmh0eVywZxLxBOoSBdb/5lNlPmpW9Sfd8F1DIqRS0pkE0l

Imi trebuie adaugata cheia assta de ssh. Eu am uitat parola la cloud:D

**Comment by MihaiBalint** [comment]
done
